### ISSUE TITLE
Beware of Broken and Pasted Code!

### ISSUE THREAD

**Issue by ApfelTeeSaft** [MarvelcoOGFN/Ero-gameserver#4]
This Repo is a Prime example of a skidded GS, the "changes" he made involve either just changing a singular string (e.g battle bus skins), or the changes are chatGPT generated, the "AI Rewrite" crashes the Server and just looks AI Generated. Looks like someone that only knows C++ tried to do an AI section for a Gameserver (ChatGPT) aka, Marvelcos best buddy.

I also just remembered what a horrible human being he is, as you can see on these screenshots someone has leaked online: https://marvelco.uk/

do not trust this kid, he is a walking sack of lies to try and keep his image up

**Comment by ApfelTeeSaft** [comment]
Thanks to FortOGFN that i even found out about this LMFAO

**Comment by MarvelcoOGFN** [comment]
> Thanks to FortOGFN that i even found out about this LMFAO

bruh tf you yapping about ai generated also i never rewrote ai i changed there skin and it doesnt crash also i never sent those messages you facked them asshole

**Comment by MarvelcoOGFN** [comment]
also bro your a fucking pedo

**Comment by ApfelTeeSaft** [comment]
> > Thanks to FortOGFN that i even found out about this LMFAO
> 
> 
> 
> bruh tf you yapping about ai generated also i never rewrote ai i changed there skin and it doesnt crash also i never sent those messages you facked them asshole
> 
> 

You said this was a rewrite, the only thing changed is maybe 2 strings

**Comment by ApfelTeeSaft** [comment]
> also bro your a fucking pedo

Also, that allegation was proven to be false but aigt, also I wouldn't be so disrespectful, everyone knows ur from Lebanon and it's not that big of a country my guy

**Comment by MarvelcoOGFN** [comment]
> > > Thanks to FortOGFN that i even found out about this LMFAO
> > 
> > 
> > bruh tf you yapping about ai generated also i never rewrote ai i changed there skin and it doesnt crash also i never sent those messages you facked them asshole
> 
> You said this was a rewrite, the only thing changed is maybe 2 strings

if you checked the fucking commits you will see what i changed and added 💀

**Comment by MarvelcoOGFN** [comment]
> > also bro your a fucking pedo
> 
> Also, that allegation was proven to be false but aigt, also I wouldn't be so disrespectful, everyone knows ur from Lebanon and it's not that big of a country my guy

and?

**Comment by ApfelTeeSaft** [comment]
> > > > Thanks to FortOGFN that i even found out about this LMFAO
> > > 
> > > 
> > > bruh tf you yapping about ai generated also i never rewrote ai i changed there skin and it doesnt crash also i never sent those messages you facked them asshole
> > 
> > 
> > You said this was a rewrite, the only thing changed is maybe 2 strings
> 
> if you checked the fucking commits you will see what i changed and added 💀

crazy, you uncommented existing code (probably why it crashes lol), and changed some floats, crazy rewrite

**Comment by MarvelcoOGFN** [comment]
> > > Thanks to FortOGFN that i even found out about this LMFAO
> > 
> > 
> > bruh tf you yapping about ai generated also i never rewrote ai i changed there skin and it doesnt crash also i never sent those messages you facked them asshole
> 
> You said this was a rewrite, the only thing changed is maybe 2 strings

a

> > > > > Thanks to FortOGFN that i even found out about this LMFAO
> > > > 
> > > > 
> > > > bruh tf you yapping about ai generated also i never rewrote ai i changed there skin and it doesnt crash also i never sent those messages you facked them asshole
> > > 
> > > 
> > > You said this was a rewrite, the only thing changed is maybe 2 strings
> > 
> > 
> > if you checked the fucking commits you will see what i changed and added 💀
> 
> crazy, you uncommented existing code (probably why it crashes lol), and changed some floats, crazy rewrite

bro only say two commits

**Comment by MarvelcoOGFN** [comment]
you relize there are 50 commits right?

**Comment by MarvelcoOGFN** [comment]
bro stoped yapping

**Comment by MarvelcoOGFN** [comment]
@ApfelTeeSaft i recomend you to stop spreading lies about me and move the fuck on you fucking retard and yes i said retard screen shot it all you want i dont fucking care

**Comment by boostedcc** [comment]
Hi nothing of this Code is skid or pasted u fucking retarded @MarvelcoOGFN self Code It i Talk to hem and i see how he do It ur iq is just 0 and u prob dont know how gs work chat gpt wont do nothing

**Comment by max8447** [comment]
NAH HE GOT ELW TO HELP HIM

**Comment by ApfelTeeSaft** [comment]
> NAH HE GOT ELW TO HELP HIM

xD

**Comment by ApfelTeeSaft** [comment]
> NAH HE GOT ELW TO HELP HIM

but you agree that everything changed here is pasted / just random ass value changes that are not needed and break everything right?

**Comment by max8447** [comment]
yes hes a skidder, and elw is too

**Comment by MarvelcoOGFN** [comment]
@ApfelTeeSaft https://github.com/MarvelcoOGFN/Apfelteesaft-exposed- enjoy this

**Comment by MarvelcoOGFN** [comment]
@ApfelTeeSaft also what ever you do i will never quit ogfn so beat it

**Comment by max8447** [comment]
wow you really exposed him with this one! great job! he will never be able to recover from this

**Comment by ApfelTeeSaft** [comment]
> @ApfelTeeSaft also what ever you do i will never quit ogfn so beat it



> wow you really exposed him with this one! great job! he will never be able to recover from this

i'll just submit another dmca takedown lol, if that goes through, his github account has 3 strikes and should technically be deleted

**Comment by ApfelTeeSaft** [comment]
> @ApfelTeeSaft also what ever you do i will never quit ogfn so beat it

also, you don't have to go crying to canel, if you want something from me, don't tell ur "bodyguard" to tell me, i never blocked you, you can also message me you braindead idiot

**Comment by max8447** [comment]
![image](https://github.com/user-attachments/assets/a03331f3-ba06-4f75-a115-4291ffeb261e)

**Comment by ApfelTeeSaft** [comment]
> ![image](https://private-user-images.githubusercontent.com/96658744/366166916-a03331f3-ba06-4f75-a115-4291ffeb261e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTUzNTcsIm5iZiI6MTcyNTk5NTA1NywicGF0aCI6Ii85NjY1ODc0NC8zNjYxNjY5MTYtYTAzMzMxZjMtYmEwNi00Zjc1LWExMTUtNDI5MWZmZWIyNjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE5MDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODFkZWIxOWI0OTVhZjlmNDY4ZmYwZjM1YmEyY2FhMDJiMDIzZDVkOWMyYjI0MDY3NWJiM2ZiZjVlNzQ5YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OBwQDuZzchjY6Qai_EUYtthcn6Wpl-xtheYe4oSPrh8)

damn, that describes him really well lol

**Comment by max8447** [comment]
> > @ApfelTeeSaft also what ever you do i will never quit ogfn so beat it
> 
> > wow you really exposed him with this one! great job! he will never be able to recover from this
> 
> i'll just submit another dmca takedown lol, if that goes through, his github account has 3 strikes and should technically be deleted

To take down what

**Comment by boostedcc** [comment]
bubs dont see anybody is talking anymore at they 🔥

**Comment by boostedcc** [comment]
max go skid reboot abit  or twin base s13

**Comment by ApfelTeeSaft** [comment]
> max go skid reboot abit  or twin base s13
> 
> 

You go and learn proper English first please

**Comment by endlessalpacaYT** [comment]
yo

**Comment by max8447** [comment]
> max go skid reboot abit or twin base s13

Funny to hear that coming from you, elw

**Comment by boostedcc** [comment]
1 i not elw where is ur poof bc nothing is same as hem
2 ur a reboot skid
3 u use twin1 base to make the clestial paste

**Comment by boostedcc** [comment]
4 kys anybody will care if u die ur mum will be happy
